// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a50tcsg324-2l,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.012000,HLS_SYN_LAT=203906,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        image_r_address0,
        image_r_ce0,
        image_r_q0,
        ret,
        ret_ap_vld
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b00000;
parameter    ap_ST_st2_fsm_1 = 5'b1;
parameter    ap_ST_st3_fsm_2 = 5'b10;
parameter    ap_ST_st4_fsm_3 = 5'b11;
parameter    ap_ST_st5_fsm_4 = 5'b100;
parameter    ap_ST_st6_fsm_5 = 5'b101;
parameter    ap_ST_st7_fsm_6 = 5'b110;
parameter    ap_ST_st8_fsm_7 = 5'b111;
parameter    ap_ST_st9_fsm_8 = 5'b1000;
parameter    ap_ST_st10_fsm_9 = 5'b1001;
parameter    ap_ST_st11_fsm_10 = 5'b1010;
parameter    ap_ST_st12_fsm_11 = 5'b1011;
parameter    ap_ST_st13_fsm_12 = 5'b1100;
parameter    ap_ST_pp0_stg0_fsm_13 = 5'b1101;
parameter    ap_ST_st16_fsm_14 = 5'b1110;
parameter    ap_ST_st17_fsm_15 = 5'b1111;
parameter    ap_ST_st18_fsm_16 = 5'b10000;
parameter    ap_ST_st19_fsm_17 = 5'b10001;
parameter    ap_ST_st20_fsm_18 = 5'b10010;
parameter    ap_ST_st21_fsm_19 = 5'b10011;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv4_5 = 4'b101;
parameter    ap_const_lv4_7 = 4'b111;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv5_1C = 5'b11100;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv9_1F4 = 9'b111110100;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] image_r_address0;
output   image_r_ce0;
input  [31:0] image_r_q0;
output  [31:0] ret;
output   ret_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg image_r_ce0;
reg ret_ap_vld;
reg   [4:0] ap_CS_fsm = 5'b00000;
reg   [9:0] I_address0;
reg    I_ce0;
reg    I_we0;
wire   [31:0] I_d0;
wire   [31:0] I_q0;
wire   [9:0] I_address1;
reg    I_ce1;
wire   [31:0] I_q1;
reg   [13:0] L1_address0;
reg    L1_ce0;
reg    L1_we0;
wire   [28:0] L1_d0;
wire   [28:0] L1_q0;
wire   [13:0] L1_address1;
reg    L1_ce1;
wire   [28:0] L1_q1;
reg   [11:0] L2_address0;
reg    L2_ce0;
reg    L2_we0;
wire   [31:0] L2_d0;
wire   [31:0] L2_q0;
reg   [11:0] L2_address1;
reg    L2_ce1;
reg    L2_we1;
wire   [31:0] L2_d1;
wire   [31:0] L2_q1;
reg   [11:0] L3_address0;
reg    L3_ce0;
reg    L3_we0;
wire   [31:0] L3_d0;
wire   [31:0] L3_q0;
wire   [11:0] L3_address1;
reg    L3_ce1;
wire   [31:0] L3_q1;
reg   [8:0] L5_address0;
reg    L5_ce0;
reg    L5_we0;
wire   [31:0] L5_d0;
wire   [31:0] L5_q0;
reg   [9:0] L4_address0;
reg    L4_ce0;
reg    L4_we0;
wire   [31:0] L4_d0;
wire   [31:0] L4_q0;
reg   [9:0] L4_address1;
reg    L4_ce1;
reg    L4_we1;
wire   [31:0] L4_d1;
wire   [31:0] L4_q1;
reg   [3:0] O_address0;
reg    O_ce0;
reg    O_we0;
wire   [31:0] O_d0;
wire   [31:0] O_q0;
reg   [8:0] L6_address0;
reg    L6_ce0;
reg    L6_we0;
wire   [30:0] L6_d0;
wire   [30:0] L6_q0;
wire   [8:0] L6_address1;
reg    L6_ce1;
wire   [30:0] L6_q1;
reg   [8:0] d0_i_reg_833;
wire   [4:0] i_1_fu_1577_p2;
reg   [4:0] i_1_reg_1747;
wire   [10:0] tmp_fu_1607_p2;
reg   [10:0] tmp_reg_1752;
wire   [0:0] exitcond2_fu_1571_p2;
wire   [4:0] j_1_fu_1623_p2;
reg   [4:0] j_1_reg_1761;
wire   [0:0] exitcond1_fu_1617_p2;
wire   [11:0] I_addr2_fu_1650_p2;
reg   [11:0] I_addr2_reg_1771;
wire   [0:0] exitcond_i_fu_1664_p2;
reg   [0:0] exitcond_i_reg_1776;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [8:0] d0_fu_1670_p2;
wire   [63:0] tmp_i_fu_1676_p1;
reg   [63:0] tmp_i_reg_1785;
wire   [31:0] n_1_cast1_fu_1702_p1;
reg   [31:0] n_1_cast1_reg_1800;
wire   [0:0] exitcond_fu_1706_p2;
wire   [3:0] i_2_fu_1717_p2;
reg   [3:0] i_2_reg_1813;
wire   [31:0] max_2_max1_fu_1729_p3;
wire   [31:0] n_2_n_fu_1737_p3;
wire    grp_conv_fu_879_ap_done;
wire    grp_conv_fu_879_ap_start;
wire    grp_conv_fu_879_ap_idle;
wire    grp_conv_fu_879_ap_ready;
reg   [3:0] grp_conv_fu_879_L;
wire   [9:0] grp_conv_fu_879_I_address0;
wire    grp_conv_fu_879_I_ce0;
wire   [31:0] grp_conv_fu_879_I_q0;
wire   [9:0] grp_conv_fu_879_I_address1;
wire    grp_conv_fu_879_I_ce1;
wire   [31:0] grp_conv_fu_879_I_q1;
wire   [13:0] grp_conv_fu_879_L1_address0;
wire    grp_conv_fu_879_L1_ce0;
wire    grp_conv_fu_879_L1_we0;
wire   [28:0] grp_conv_fu_879_L1_d0;
wire   [11:0] grp_conv_fu_879_L2_address0;
wire    grp_conv_fu_879_L2_ce0;
wire   [31:0] grp_conv_fu_879_L2_q0;
wire   [11:0] grp_conv_fu_879_L2_address1;
wire    grp_conv_fu_879_L2_ce1;
wire   [31:0] grp_conv_fu_879_L2_q1;
wire   [11:0] grp_conv_fu_879_L3_address0;
wire    grp_conv_fu_879_L3_ce0;
wire    grp_conv_fu_879_L3_we0;
wire   [31:0] grp_conv_fu_879_L3_d0;
wire   [8:0] grp_conv_fu_879_L5_address0;
wire    grp_conv_fu_879_L5_ce0;
wire    grp_conv_fu_879_L5_we0;
wire   [31:0] grp_conv_fu_879_L5_d0;
wire   [9:0] grp_conv_fu_879_L4_address0;
wire    grp_conv_fu_879_L4_ce0;
wire   [31:0] grp_conv_fu_879_L4_q0;
wire   [9:0] grp_conv_fu_879_L4_address1;
wire    grp_conv_fu_879_L4_ce1;
wire   [31:0] grp_conv_fu_879_L4_q1;
wire   [3:0] grp_conv_fu_879_O_address0;
wire    grp_conv_fu_879_O_ce0;
wire    grp_conv_fu_879_O_we0;
wire   [31:0] grp_conv_fu_879_O_d0;
wire   [8:0] grp_conv_fu_879_L6_address0;
wire    grp_conv_fu_879_L6_ce0;
wire   [30:0] grp_conv_fu_879_L6_q0;
wire   [8:0] grp_conv_fu_879_L6_address1;
wire    grp_conv_fu_879_L6_ce1;
wire   [30:0] grp_conv_fu_879_L6_q1;
wire    grp_pool_fu_1556_ap_start;
wire    grp_pool_fu_1556_ap_done;
wire    grp_pool_fu_1556_ap_idle;
wire    grp_pool_fu_1556_ap_ready;
reg   [3:0] grp_pool_fu_1556_L;
wire   [13:0] grp_pool_fu_1556_L1_address0;
wire    grp_pool_fu_1556_L1_ce0;
wire   [28:0] grp_pool_fu_1556_L1_q0;
wire   [13:0] grp_pool_fu_1556_L1_address1;
wire    grp_pool_fu_1556_L1_ce1;
wire   [28:0] grp_pool_fu_1556_L1_q1;
wire   [11:0] grp_pool_fu_1556_L2_address0;
wire    grp_pool_fu_1556_L2_ce0;
wire    grp_pool_fu_1556_L2_we0;
wire   [31:0] grp_pool_fu_1556_L2_d0;
wire   [11:0] grp_pool_fu_1556_L2_address1;
wire    grp_pool_fu_1556_L2_ce1;
wire    grp_pool_fu_1556_L2_we1;
wire   [31:0] grp_pool_fu_1556_L2_d1;
wire   [31:0] grp_pool_fu_1556_L2_q1;
wire   [11:0] grp_pool_fu_1556_L3_address0;
wire    grp_pool_fu_1556_L3_ce0;
wire   [31:0] grp_pool_fu_1556_L3_q0;
wire   [11:0] grp_pool_fu_1556_L3_address1;
wire    grp_pool_fu_1556_L3_ce1;
wire   [31:0] grp_pool_fu_1556_L3_q1;
wire   [9:0] grp_pool_fu_1556_L4_address0;
wire    grp_pool_fu_1556_L4_ce0;
wire    grp_pool_fu_1556_L4_we0;
wire   [31:0] grp_pool_fu_1556_L4_d0;
wire   [9:0] grp_pool_fu_1556_L4_address1;
wire    grp_pool_fu_1556_L4_ce1;
wire    grp_pool_fu_1556_L4_we1;
wire   [31:0] grp_pool_fu_1556_L4_d1;
wire   [31:0] grp_pool_fu_1556_L4_q1;
reg   [4:0] i_reg_811;
reg   [4:0] j_reg_822;
reg   [31:0] max1_reg_844;
reg   [31:0] n_reg_854;
reg   [3:0] n_1_reg_867;
reg    grp_conv_fu_879_ap_start_ap_start_reg = 1'b0;
reg    grp_pool_fu_1556_ap_start_ap_start_reg = 1'b0;
wire   [63:0] tmp_2_fu_1638_p1;
wire   [63:0] tmp_7_fu_1659_p1;
wire   [63:0] tmp_4_fu_1712_p1;
wire   [9:0] p_shl_fu_1583_p3;
wire   [6:0] p_shl2_fu_1595_p3;
wire   [10:0] p_shl_cast_fu_1591_p1;
wire   [10:0] p_shl2_cast_fu_1603_p1;
wire   [10:0] j_cast4_fu_1613_p1;
wire   [10:0] tmp_1_fu_1629_p2;
wire   [31:0] tmp_2_fu_1638_p0;
wire   [11:0] I_addr2_fu_1650_p0;
wire   [11:0] tmp_3_trn_cast_fu_1643_p1;
wire   [31:0] tmp_7_fu_1659_p0;
wire   [0:0] tmp_6_fu_1685_p3;
wire   [30:0] tmp_3_fu_1681_p1;
wire   [0:0] tmp_5_fu_1723_p2;
reg   [4:0] ap_NS_fsm;


top_I #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
I_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( I_address0 ),
    .ce0( I_ce0 ),
    .we0( I_we0 ),
    .d0( I_d0 ),
    .q0( I_q0 ),
    .address1( I_address1 ),
    .ce1( I_ce1 ),
    .q1( I_q1 )
);

top_L1 #(
    .DataWidth( 29 ),
    .AddressRange( 11520 ),
    .AddressWidth( 14 ))
L1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( L1_address0 ),
    .ce0( L1_ce0 ),
    .we0( L1_we0 ),
    .d0( L1_d0 ),
    .q0( L1_q0 ),
    .address1( L1_address1 ),
    .ce1( L1_ce1 ),
    .q1( L1_q1 )
);

top_L2 #(
    .DataWidth( 32 ),
    .AddressRange( 2880 ),
    .AddressWidth( 12 ))
L2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( L2_address0 ),
    .ce0( L2_ce0 ),
    .we0( L2_we0 ),
    .d0( L2_d0 ),
    .q0( L2_q0 ),
    .address1( L2_address1 ),
    .ce1( L2_ce1 ),
    .we1( L2_we1 ),
    .d1( L2_d1 ),
    .q1( L2_q1 )
);

top_L3 #(
    .DataWidth( 32 ),
    .AddressRange( 3200 ),
    .AddressWidth( 12 ))
L3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( L3_address0 ),
    .ce0( L3_ce0 ),
    .we0( L3_we0 ),
    .d0( L3_d0 ),
    .q0( L3_q0 ),
    .address1( L3_address1 ),
    .ce1( L3_ce1 ),
    .q1( L3_q1 )
);

top_L5 #(
    .DataWidth( 32 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
L5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( L5_address0 ),
    .ce0( L5_ce0 ),
    .we0( L5_we0 ),
    .d0( L5_d0 ),
    .q0( L5_q0 )
);

top_L4 #(
    .DataWidth( 32 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
L4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( L4_address0 ),
    .ce0( L4_ce0 ),
    .we0( L4_we0 ),
    .d0( L4_d0 ),
    .q0( L4_q0 ),
    .address1( L4_address1 ),
    .ce1( L4_ce1 ),
    .we1( L4_we1 ),
    .d1( L4_d1 ),
    .q1( L4_q1 )
);

top_O #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
O_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( O_address0 ),
    .ce0( O_ce0 ),
    .we0( O_we0 ),
    .d0( O_d0 ),
    .q0( O_q0 )
);

top_L6 #(
    .DataWidth( 31 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
L6_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( L6_address0 ),
    .ce0( L6_ce0 ),
    .we0( L6_we0 ),
    .d0( L6_d0 ),
    .q0( L6_q0 ),
    .address1( L6_address1 ),
    .ce1( L6_ce1 ),
    .q1( L6_q1 )
);

conv grp_conv_fu_879(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_conv_fu_879_ap_start ),
    .ap_done( grp_conv_fu_879_ap_done ),
    .ap_idle( grp_conv_fu_879_ap_idle ),
    .ap_ready( grp_conv_fu_879_ap_ready ),
    .L( grp_conv_fu_879_L ),
    .I_address0( grp_conv_fu_879_I_address0 ),
    .I_ce0( grp_conv_fu_879_I_ce0 ),
    .I_q0( grp_conv_fu_879_I_q0 ),
    .I_address1( grp_conv_fu_879_I_address1 ),
    .I_ce1( grp_conv_fu_879_I_ce1 ),
    .I_q1( grp_conv_fu_879_I_q1 ),
    .L1_address0( grp_conv_fu_879_L1_address0 ),
    .L1_ce0( grp_conv_fu_879_L1_ce0 ),
    .L1_we0( grp_conv_fu_879_L1_we0 ),
    .L1_d0( grp_conv_fu_879_L1_d0 ),
    .L2_address0( grp_conv_fu_879_L2_address0 ),
    .L2_ce0( grp_conv_fu_879_L2_ce0 ),
    .L2_q0( grp_conv_fu_879_L2_q0 ),
    .L2_address1( grp_conv_fu_879_L2_address1 ),
    .L2_ce1( grp_conv_fu_879_L2_ce1 ),
    .L2_q1( grp_conv_fu_879_L2_q1 ),
    .L3_address0( grp_conv_fu_879_L3_address0 ),
    .L3_ce0( grp_conv_fu_879_L3_ce0 ),
    .L3_we0( grp_conv_fu_879_L3_we0 ),
    .L3_d0( grp_conv_fu_879_L3_d0 ),
    .L5_address0( grp_conv_fu_879_L5_address0 ),
    .L5_ce0( grp_conv_fu_879_L5_ce0 ),
    .L5_we0( grp_conv_fu_879_L5_we0 ),
    .L5_d0( grp_conv_fu_879_L5_d0 ),
    .L4_address0( grp_conv_fu_879_L4_address0 ),
    .L4_ce0( grp_conv_fu_879_L4_ce0 ),
    .L4_q0( grp_conv_fu_879_L4_q0 ),
    .L4_address1( grp_conv_fu_879_L4_address1 ),
    .L4_ce1( grp_conv_fu_879_L4_ce1 ),
    .L4_q1( grp_conv_fu_879_L4_q1 ),
    .O_address0( grp_conv_fu_879_O_address0 ),
    .O_ce0( grp_conv_fu_879_O_ce0 ),
    .O_we0( grp_conv_fu_879_O_we0 ),
    .O_d0( grp_conv_fu_879_O_d0 ),
    .L6_address0( grp_conv_fu_879_L6_address0 ),
    .L6_ce0( grp_conv_fu_879_L6_ce0 ),
    .L6_q0( grp_conv_fu_879_L6_q0 ),
    .L6_address1( grp_conv_fu_879_L6_address1 ),
    .L6_ce1( grp_conv_fu_879_L6_ce1 ),
    .L6_q1( grp_conv_fu_879_L6_q1 )
);

pool grp_pool_fu_1556(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_pool_fu_1556_ap_start ),
    .ap_done( grp_pool_fu_1556_ap_done ),
    .ap_idle( grp_pool_fu_1556_ap_idle ),
    .ap_ready( grp_pool_fu_1556_ap_ready ),
    .L( grp_pool_fu_1556_L ),
    .L1_address0( grp_pool_fu_1556_L1_address0 ),
    .L1_ce0( grp_pool_fu_1556_L1_ce0 ),
    .L1_q0( grp_pool_fu_1556_L1_q0 ),
    .L1_address1( grp_pool_fu_1556_L1_address1 ),
    .L1_ce1( grp_pool_fu_1556_L1_ce1 ),
    .L1_q1( grp_pool_fu_1556_L1_q1 ),
    .L2_address0( grp_pool_fu_1556_L2_address0 ),
    .L2_ce0( grp_pool_fu_1556_L2_ce0 ),
    .L2_we0( grp_pool_fu_1556_L2_we0 ),
    .L2_d0( grp_pool_fu_1556_L2_d0 ),
    .L2_address1( grp_pool_fu_1556_L2_address1 ),
    .L2_ce1( grp_pool_fu_1556_L2_ce1 ),
    .L2_we1( grp_pool_fu_1556_L2_we1 ),
    .L2_d1( grp_pool_fu_1556_L2_d1 ),
    .L2_q1( grp_pool_fu_1556_L2_q1 ),
    .L3_address0( grp_pool_fu_1556_L3_address0 ),
    .L3_ce0( grp_pool_fu_1556_L3_ce0 ),
    .L3_q0( grp_pool_fu_1556_L3_q0 ),
    .L3_address1( grp_pool_fu_1556_L3_address1 ),
    .L3_ce1( grp_pool_fu_1556_L3_ce1 ),
    .L3_q1( grp_pool_fu_1556_L3_q1 ),
    .L4_address0( grp_pool_fu_1556_L4_address0 ),
    .L4_ce0( grp_pool_fu_1556_L4_ce0 ),
    .L4_we0( grp_pool_fu_1556_L4_we0 ),
    .L4_d0( grp_pool_fu_1556_L4_d0 ),
    .L4_address1( grp_pool_fu_1556_L4_address1 ),
    .L4_ce1( grp_pool_fu_1556_L4_ce1 ),
    .L4_we1( grp_pool_fu_1556_L4_we1 ),
    .L4_d1( grp_pool_fu_1556_L4_d1 ),
    .L4_q1( grp_pool_fu_1556_L4_q1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_i_fu_1664_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_conv_fu_879_ap_done))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_i_fu_1664_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st13_fsm_12 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_conv_fu_879_ap_done)) | ((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_i_fu_1664_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// grp_conv_fu_879_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_conv_fu_879_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_conv_fu_879_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond2_fu_1571_p2 == ap_const_lv1_0)) | (ap_ST_st8_fsm_7 == ap_CS_fsm) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st16_fsm_14 == ap_CS_fsm))) begin
            grp_conv_fu_879_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_conv_fu_879_ap_ready)) begin
            grp_conv_fu_879_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// grp_pool_fu_1556_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_pool_fu_1556_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_pool_fu_1556_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st6_fsm_5 == ap_CS_fsm) | (ap_ST_st10_fsm_9 == ap_CS_fsm))) begin
            grp_pool_fu_1556_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_pool_fu_1556_ap_ready)) begin
            grp_pool_fu_1556_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_lv1_0 == exitcond_i_fu_1664_p2))) begin
        d0_i_reg_833 <= d0_fu_1670_p2;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_conv_fu_879_ap_done))) begin
        d0_i_reg_833 <= ap_const_lv9_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_1617_p2))) begin
        i_reg_811 <= i_1_reg_1747;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        i_reg_811 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond2_fu_1571_p2 == ap_const_lv1_0))) begin
        j_reg_822 <= ap_const_lv5_0;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        j_reg_822 <= j_1_reg_1761;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st21_fsm_19 == ap_CS_fsm)) begin
        max1_reg_844 <= max_2_max1_fu_1729_p3;
    end else if ((ap_ST_st19_fsm_17 == ap_CS_fsm)) begin
        max1_reg_844 <= O_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st21_fsm_19 == ap_CS_fsm)) begin
        n_1_reg_867 <= i_2_reg_1813;
    end else if ((ap_ST_st19_fsm_17 == ap_CS_fsm)) begin
        n_1_reg_867 <= ap_const_lv4_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st21_fsm_19 == ap_CS_fsm)) begin
        n_reg_854 <= n_2_n_fu_1737_p3;
    end else if ((ap_ST_st19_fsm_17 == ap_CS_fsm)) begin
        n_reg_854 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_1617_p2))) begin
        I_addr2_reg_1771 <= I_addr2_fu_1650_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        exitcond_i_reg_1776 <= exitcond_i_fu_1664_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_1_reg_1747 <= i_1_fu_1577_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_18 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_1706_p2))) begin
        i_2_reg_1813 <= i_2_fu_1717_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        j_1_reg_1761 <= j_1_fu_1623_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st20_fsm_18 == ap_CS_fsm)) begin
        n_1_cast1_reg_1800[0] <= n_1_cast1_fu_1702_p1[0];
n_1_cast1_reg_1800[1] <= n_1_cast1_fu_1702_p1[1];
n_1_cast1_reg_1800[2] <= n_1_cast1_fu_1702_p1[2];
n_1_cast1_reg_1800[3] <= n_1_cast1_fu_1702_p1[3];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_lv1_0 == exitcond_i_fu_1664_p2))) begin
        tmp_i_reg_1785[0] <= tmp_i_fu_1676_p1[0];
tmp_i_reg_1785[1] <= tmp_i_fu_1676_p1[1];
tmp_i_reg_1785[2] <= tmp_i_fu_1676_p1[2];
tmp_i_reg_1785[3] <= tmp_i_fu_1676_p1[3];
tmp_i_reg_1785[4] <= tmp_i_fu_1676_p1[4];
tmp_i_reg_1785[5] <= tmp_i_fu_1676_p1[5];
tmp_i_reg_1785[6] <= tmp_i_fu_1676_p1[6];
tmp_i_reg_1785[7] <= tmp_i_fu_1676_p1[7];
tmp_i_reg_1785[8] <= tmp_i_fu_1676_p1[8];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond2_fu_1571_p2 == ap_const_lv1_0))) begin
        tmp_reg_1752[2] <= tmp_fu_1607_p2[2];
tmp_reg_1752[3] <= tmp_fu_1607_p2[3];
tmp_reg_1752[4] <= tmp_fu_1607_p2[4];
tmp_reg_1752[5] <= tmp_fu_1607_p2[5];
tmp_reg_1752[6] <= tmp_fu_1607_p2[6];
tmp_reg_1752[7] <= tmp_fu_1607_p2[7];
tmp_reg_1752[8] <= tmp_fu_1607_p2[8];
tmp_reg_1752[9] <= tmp_fu_1607_p2[9];
tmp_reg_1752[10] <= tmp_fu_1607_p2[10];
    end
end

/// I_address0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_I_address0 or tmp_7_fu_1659_p1)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        I_address0 = tmp_7_fu_1659_p1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        I_address0 = grp_conv_fu_879_I_address0;
    end else begin
        I_address0 = 'bx;
    end
end

/// I_ce0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_I_ce0)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        I_ce0 = ap_const_logic_1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        I_ce0 = grp_conv_fu_879_I_ce0;
    end else begin
        I_ce0 = ap_const_logic_0;
    end
end

/// I_ce1 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_I_ce1)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        I_ce1 = grp_conv_fu_879_I_ce1;
    end else begin
        I_ce1 = ap_const_logic_0;
    end
end

/// I_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        I_we0 = ap_const_logic_1;
    end else begin
        I_we0 = ap_const_logic_0;
    end
end

/// L1_address0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L1_address0 or grp_pool_fu_1556_L1_address0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L1_address0 = grp_pool_fu_1556_L1_address0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L1_address0 = grp_conv_fu_879_L1_address0;
    end else begin
        L1_address0 = 'bx;
    end
end

/// L1_ce0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L1_ce0 or grp_pool_fu_1556_L1_ce0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L1_ce0 = grp_pool_fu_1556_L1_ce0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L1_ce0 = grp_conv_fu_879_L1_ce0;
    end else begin
        L1_ce0 = ap_const_logic_0;
    end
end

/// L1_ce1 assign process. ///
always @ (ap_CS_fsm or grp_pool_fu_1556_L1_ce1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L1_ce1 = grp_pool_fu_1556_L1_ce1;
    end else begin
        L1_ce1 = ap_const_logic_0;
    end
end

/// L1_we0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L1_we0)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L1_we0 = grp_conv_fu_879_L1_we0;
    end else begin
        L1_we0 = ap_const_logic_0;
    end
end

/// L2_address0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L2_address0 or grp_pool_fu_1556_L2_address0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L2_address0 = grp_pool_fu_1556_L2_address0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L2_address0 = grp_conv_fu_879_L2_address0;
    end else begin
        L2_address0 = 'bx;
    end
end

/// L2_address1 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L2_address1 or grp_pool_fu_1556_L2_address1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L2_address1 = grp_pool_fu_1556_L2_address1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L2_address1 = grp_conv_fu_879_L2_address1;
    end else begin
        L2_address1 = 'bx;
    end
end

/// L2_ce0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L2_ce0 or grp_pool_fu_1556_L2_ce0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L2_ce0 = grp_pool_fu_1556_L2_ce0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L2_ce0 = grp_conv_fu_879_L2_ce0;
    end else begin
        L2_ce0 = ap_const_logic_0;
    end
end

/// L2_ce1 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L2_ce1 or grp_pool_fu_1556_L2_ce1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L2_ce1 = grp_pool_fu_1556_L2_ce1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L2_ce1 = grp_conv_fu_879_L2_ce1;
    end else begin
        L2_ce1 = ap_const_logic_0;
    end
end

/// L2_we0 assign process. ///
always @ (ap_CS_fsm or grp_pool_fu_1556_L2_we0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L2_we0 = grp_pool_fu_1556_L2_we0;
    end else begin
        L2_we0 = ap_const_logic_0;
    end
end

/// L2_we1 assign process. ///
always @ (ap_CS_fsm or grp_pool_fu_1556_L2_we1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L2_we1 = grp_pool_fu_1556_L2_we1;
    end else begin
        L2_we1 = ap_const_logic_0;
    end
end

/// L3_address0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L3_address0 or grp_pool_fu_1556_L3_address0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L3_address0 = grp_pool_fu_1556_L3_address0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L3_address0 = grp_conv_fu_879_L3_address0;
    end else begin
        L3_address0 = 'bx;
    end
end

/// L3_ce0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L3_ce0 or grp_pool_fu_1556_L3_ce0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L3_ce0 = grp_pool_fu_1556_L3_ce0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L3_ce0 = grp_conv_fu_879_L3_ce0;
    end else begin
        L3_ce0 = ap_const_logic_0;
    end
end

/// L3_ce1 assign process. ///
always @ (ap_CS_fsm or grp_pool_fu_1556_L3_ce1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L3_ce1 = grp_pool_fu_1556_L3_ce1;
    end else begin
        L3_ce1 = ap_const_logic_0;
    end
end

/// L3_we0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L3_we0)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L3_we0 = grp_conv_fu_879_L3_we0;
    end else begin
        L3_we0 = ap_const_logic_0;
    end
end

/// L4_address0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L4_address0 or grp_pool_fu_1556_L4_address0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L4_address0 = grp_pool_fu_1556_L4_address0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L4_address0 = grp_conv_fu_879_L4_address0;
    end else begin
        L4_address0 = 'bx;
    end
end

/// L4_address1 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L4_address1 or grp_pool_fu_1556_L4_address1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L4_address1 = grp_pool_fu_1556_L4_address1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L4_address1 = grp_conv_fu_879_L4_address1;
    end else begin
        L4_address1 = 'bx;
    end
end

/// L4_ce0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L4_ce0 or grp_pool_fu_1556_L4_ce0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L4_ce0 = grp_pool_fu_1556_L4_ce0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L4_ce0 = grp_conv_fu_879_L4_ce0;
    end else begin
        L4_ce0 = ap_const_logic_0;
    end
end

/// L4_ce1 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L4_ce1 or grp_pool_fu_1556_L4_ce1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L4_ce1 = grp_pool_fu_1556_L4_ce1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L4_ce1 = grp_conv_fu_879_L4_ce1;
    end else begin
        L4_ce1 = ap_const_logic_0;
    end
end

/// L4_we0 assign process. ///
always @ (ap_CS_fsm or grp_pool_fu_1556_L4_we0)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L4_we0 = grp_pool_fu_1556_L4_we0;
    end else begin
        L4_we0 = ap_const_logic_0;
    end
end

/// L4_we1 assign process. ///
always @ (ap_CS_fsm or grp_pool_fu_1556_L4_we1)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        L4_we1 = grp_pool_fu_1556_L4_we1;
    end else begin
        L4_we1 = ap_const_logic_0;
    end
end

/// L5_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or tmp_i_fu_1676_p1 or grp_conv_fu_879_L5_address0)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        L5_address0 = tmp_i_fu_1676_p1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L5_address0 = grp_conv_fu_879_L5_address0;
    end else begin
        L5_address0 = 'bx;
    end
end

/// L5_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or grp_conv_fu_879_L5_ce0)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        L5_ce0 = ap_const_logic_1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L5_ce0 = grp_conv_fu_879_L5_ce0;
    end else begin
        L5_ce0 = ap_const_logic_0;
    end
end

/// L5_we0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L5_we0)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L5_we0 = grp_conv_fu_879_L5_we0;
    end else begin
        L5_we0 = ap_const_logic_0;
    end
end

/// L6_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it1 or tmp_i_reg_1785 or grp_conv_fu_879_L6_address0)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        L6_address0 = tmp_i_reg_1785;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L6_address0 = grp_conv_fu_879_L6_address0;
    end else begin
        L6_address0 = 'bx;
    end
end

/// L6_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it1 or grp_conv_fu_879_L6_ce0)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        L6_ce0 = ap_const_logic_1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L6_ce0 = grp_conv_fu_879_L6_ce0;
    end else begin
        L6_ce0 = ap_const_logic_0;
    end
end

/// L6_ce1 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_L6_ce1)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        L6_ce1 = grp_conv_fu_879_L6_ce1;
    end else begin
        L6_ce1 = ap_const_logic_0;
    end
end

/// L6_we0 assign process. ///
always @ (ap_CS_fsm or exitcond_i_reg_1776 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_13 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_lv1_0 == exitcond_i_reg_1776))) begin
        L6_we0 = ap_const_logic_1;
    end else begin
        L6_we0 = ap_const_logic_0;
    end
end

/// O_address0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_O_address0 or tmp_4_fu_1712_p1)
begin
    if ((ap_ST_st20_fsm_18 == ap_CS_fsm)) begin
        O_address0 = tmp_4_fu_1712_p1;
    end else if ((ap_ST_st18_fsm_16 == ap_CS_fsm)) begin
        O_address0 = ap_const_lv4_0;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        O_address0 = grp_conv_fu_879_O_address0;
    end else begin
        O_address0 = 'bx;
    end
end

/// O_ce0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_O_ce0)
begin
    if (((ap_ST_st20_fsm_18 == ap_CS_fsm) | (ap_ST_st18_fsm_16 == ap_CS_fsm))) begin
        O_ce0 = ap_const_logic_1;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        O_ce0 = grp_conv_fu_879_O_ce0;
    end else begin
        O_ce0 = ap_const_logic_0;
    end
end

/// O_we0 assign process. ///
always @ (ap_CS_fsm or grp_conv_fu_879_O_we0)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st17_fsm_15 == ap_CS_fsm))) begin
        O_we0 = grp_conv_fu_879_O_we0;
    end else begin
        O_we0 = ap_const_logic_0;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or exitcond_fu_1706_p2)
begin
    if (((ap_ST_st20_fsm_18 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_1706_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond_fu_1706_p2)
begin
    if (((ap_ST_st20_fsm_18 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_1706_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// grp_conv_fu_879_L assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st17_fsm_15 == ap_CS_fsm)) begin
        grp_conv_fu_879_L = ap_const_lv4_7;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        grp_conv_fu_879_L = ap_const_lv4_5;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        grp_conv_fu_879_L = ap_const_lv4_3;
    end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        grp_conv_fu_879_L = ap_const_lv4_1;
    end else begin
        grp_conv_fu_879_L = 'bx;
    end
end

/// grp_pool_fu_1556_L assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        grp_pool_fu_1556_L = ap_const_lv4_4;
    end else if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        grp_pool_fu_1556_L = ap_const_lv4_2;
    end else begin
        grp_pool_fu_1556_L = 'bx;
    end
end

/// image_r_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        image_r_ce0 = ap_const_logic_1;
    end else begin
        image_r_ce0 = ap_const_logic_0;
    end
end

/// ret_ap_vld assign process. ///
always @ (ap_CS_fsm or exitcond_fu_1706_p2)
begin
    if (((ap_ST_st20_fsm_18 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_1706_p2))) begin
        ret_ap_vld = ap_const_logic_1;
    end else begin
        ret_ap_vld = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond2_fu_1571_p2 or exitcond1_fu_1617_p2 or exitcond_i_fu_1664_p2 or ap_reg_ppiten_pp0_it0 or exitcond_fu_1706_p2 or grp_conv_fu_879_ap_done or grp_pool_fu_1556_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((exitcond2_fu_1571_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st3_fsm_2 : 
            if ((ap_const_lv1_0 == exitcond1_fu_1617_p2)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st5_fsm_4 : 
            if (~(ap_const_logic_0 == grp_conv_fu_879_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            if (~(ap_const_logic_0 == grp_pool_fu_1556_ap_done)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
        ap_ST_st9_fsm_8 : 
            if (~(ap_const_logic_0 == grp_conv_fu_879_ap_done)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            if (~(ap_const_logic_0 == grp_pool_fu_1556_ap_done)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            if (~(ap_const_logic_0 == grp_conv_fu_879_ap_done)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end
        ap_ST_pp0_stg0_fsm_13 : 
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_i_fu_1664_p2))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_14;
            end
        ap_ST_st16_fsm_14 : 
            ap_NS_fsm = ap_ST_st17_fsm_15;
        ap_ST_st17_fsm_15 : 
            if (~(ap_const_logic_0 == grp_conv_fu_879_ap_done)) begin
                ap_NS_fsm = ap_ST_st18_fsm_16;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_15;
            end
        ap_ST_st18_fsm_16 : 
            ap_NS_fsm = ap_ST_st19_fsm_17;
        ap_ST_st19_fsm_17 : 
            ap_NS_fsm = ap_ST_st20_fsm_18;
        ap_ST_st20_fsm_18 : 
            if (~(ap_const_lv1_0 == exitcond_fu_1706_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st21_fsm_19;
            end
        ap_ST_st21_fsm_19 : 
            ap_NS_fsm = ap_ST_st20_fsm_18;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign I_addr2_fu_1650_p0 = $signed(tmp_reg_1752);
assign I_addr2_fu_1650_p2 = (I_addr2_fu_1650_p0 + tmp_3_trn_cast_fu_1643_p1);
assign I_address1 = grp_conv_fu_879_I_address1;
assign I_d0 = image_r_q0;
assign L1_address1 = grp_pool_fu_1556_L1_address1;
assign L1_d0 = grp_conv_fu_879_L1_d0;
assign L2_d0 = grp_pool_fu_1556_L2_d0;
assign L2_d1 = grp_pool_fu_1556_L2_d1;
assign L3_address1 = grp_pool_fu_1556_L3_address1;
assign L3_d0 = grp_conv_fu_879_L3_d0;
assign L4_d0 = grp_pool_fu_1556_L4_d0;
assign L4_d1 = grp_pool_fu_1556_L4_d1;
assign L5_d0 = grp_conv_fu_879_L5_d0;
assign L6_address1 = grp_conv_fu_879_L6_address1;
assign L6_d0 = ((tmp_6_fu_1685_p3)? ap_const_lv31_0: tmp_3_fu_1681_p1);
assign O_d0 = grp_conv_fu_879_O_d0;
assign d0_fu_1670_p2 = (d0_i_reg_833 + ap_const_lv9_1);
assign exitcond1_fu_1617_p2 = (j_reg_822 == ap_const_lv5_1C? 1'b1: 1'b0);
assign exitcond2_fu_1571_p2 = (i_reg_811 == ap_const_lv5_1C? 1'b1: 1'b0);
assign exitcond_fu_1706_p2 = (n_1_reg_867 == ap_const_lv4_A? 1'b1: 1'b0);
assign exitcond_i_fu_1664_p2 = (d0_i_reg_833 == ap_const_lv9_1F4? 1'b1: 1'b0);
assign grp_conv_fu_879_I_q0 = I_q0;
assign grp_conv_fu_879_I_q1 = I_q1;
assign grp_conv_fu_879_L2_q0 = L2_q0;
assign grp_conv_fu_879_L2_q1 = L2_q1;
assign grp_conv_fu_879_L4_q0 = L4_q0;
assign grp_conv_fu_879_L4_q1 = L4_q1;
assign grp_conv_fu_879_L6_q0 = L6_q0;
assign grp_conv_fu_879_L6_q1 = L6_q1;
assign grp_conv_fu_879_ap_start = grp_conv_fu_879_ap_start_ap_start_reg;
assign grp_pool_fu_1556_L1_q0 = L1_q0;
assign grp_pool_fu_1556_L1_q1 = L1_q1;
assign grp_pool_fu_1556_L2_q1 = L2_q1;
assign grp_pool_fu_1556_L3_q0 = L3_q0;
assign grp_pool_fu_1556_L3_q1 = L3_q1;
assign grp_pool_fu_1556_L4_q1 = L4_q1;
assign grp_pool_fu_1556_ap_start = grp_pool_fu_1556_ap_start_ap_start_reg;
assign i_1_fu_1577_p2 = (i_reg_811 + ap_const_lv5_1);
assign i_2_fu_1717_p2 = (n_1_reg_867 + ap_const_lv4_1);
assign image_r_address0 = tmp_2_fu_1638_p1;
assign j_1_fu_1623_p2 = (j_reg_822 + ap_const_lv5_1);
assign j_cast4_fu_1613_p1 = $unsigned(j_reg_822);
assign max_2_max1_fu_1729_p3 = ((tmp_5_fu_1723_p2)? O_q0: max1_reg_844);
assign n_1_cast1_fu_1702_p1 = $unsigned(n_1_reg_867);
assign n_2_n_fu_1737_p3 = ((tmp_5_fu_1723_p2)? n_1_cast1_reg_1800: n_reg_854);
assign p_shl2_cast_fu_1603_p1 = $unsigned(p_shl2_fu_1595_p3);
assign p_shl2_fu_1595_p3 = {{i_reg_811}, {ap_const_lv2_0}};
assign p_shl_cast_fu_1591_p1 = $unsigned(p_shl_fu_1583_p3);
assign p_shl_fu_1583_p3 = {{i_reg_811}, {ap_const_lv5_0}};
assign ret = n_reg_854;
assign tmp_1_fu_1629_p2 = (j_cast4_fu_1613_p1 + tmp_reg_1752);
assign tmp_2_fu_1638_p0 = $signed(tmp_1_fu_1629_p2);
assign tmp_2_fu_1638_p1 = $unsigned(tmp_2_fu_1638_p0);
assign tmp_3_fu_1681_p1 = L5_q0[30:0];
assign tmp_3_trn_cast_fu_1643_p1 = $unsigned(j_reg_822);
assign tmp_4_fu_1712_p1 = $unsigned(n_1_reg_867);
assign tmp_5_fu_1723_p2 = ($signed(O_q0) > $signed(max1_reg_844)? 1'b1: 1'b0);
assign tmp_6_fu_1685_p3 = L5_q0[ap_const_lv32_1F];
assign tmp_7_fu_1659_p0 = $signed(I_addr2_reg_1771);
assign tmp_7_fu_1659_p1 = $unsigned(tmp_7_fu_1659_p0);
assign tmp_fu_1607_p2 = (p_shl_cast_fu_1591_p1 - p_shl2_cast_fu_1603_p1);
assign tmp_i_fu_1676_p1 = $unsigned(d0_i_reg_833);
always @ (posedge ap_clk)
begin
    tmp_reg_1752[1:0] <= 2'b00;
    tmp_i_reg_1785[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    n_1_cast1_reg_1800[31:4] <= 28'b0000000000000000000000000000;
end



endmodule //top

